# Generated by Django 3.1.2 on 2021-07-22 15:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('_path', models.CharField(default='', max_length=256)),
                ('tocken', models.CharField(default='', max_length=1024)),
                ('mntpath', models.CharField(default='', max_length=1024)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-id'],
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('task', models.CharField(max_length=128)),
                ('_path', models.CharField(default='', max_length=256)),
                ('is_check', models.BooleanField(default=False)),
                ('created_at', models.CharField(default='', max_length=256)),
                ('hyperp_path', models.CharField(default='', max_length=256)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='customize_algo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='算法名称')),
                ('version', models.CharField(blank=True, max_length=128, verbose_name='版本')),
                ('description', models.TextField(blank=True, verbose_name='算法描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('ai_engine', models.CharField(max_length=128)),
                ('project_path', models.CharField(max_length=256)),
                ('start_path', models.CharField(max_length=256)),
                ('code_path', models.CharField(max_length=256)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='customize_auto_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=64)),
                ('suggest', models.IntegerField()),
                ('epoch', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('algo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_app.customize_algo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('task', models.CharField(max_length=128)),
                ('_path', models.CharField(default='', max_length=256)),
                ('is_check', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User_algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user_id', models.IntegerField()),
                ('task', models.CharField(default='', max_length=128)),
                ('_path', models.CharField(default='', max_length=256)),
                ('created_at', models.CharField(default='', max_length=256)),
                ('hyperp_path', models.CharField(default='', max_length=256)),
                ('algorithm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_app.algorithm')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('createdTime', models.CharField(max_length=128)),
                ('completedTime', models.CharField(max_length=128)),
                ('_path', models.CharField(default='', max_length=256)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_app.user_algorithm')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_app.dataset')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='search_para',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data_type', models.CharField(max_length=64)),
                ('space', models.CharField(blank=True, max_length=64, null=True)),
                ('values', models.TextField(blank=True, max_length=2048, null=True)),
                ('ranges_max', models.CharField(blank=True, max_length=64, null=True)),
                ('ranges_min', models.CharField(blank=True, max_length=64, null=True)),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_app.customize_auto_search')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='search_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_app.customize_auto_search')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='customize_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('algo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_app.customize_algo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='algo_io',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('default_path', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('belong_algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_app.customize_algo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='algo_hpyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data_type', models.CharField(max_length=64)),
                ('initial_value', models.CharField(blank=True, max_length=256)),
                ('limitations', models.TextField(blank=True, verbose_name='Json字符串形式保存的超参限制条件')),
                ('is_necessary', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('belong_algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_app.customize_algo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
