# Generated by Django 2.2 on 2020-10-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('task', models.CharField(max_length=128)),
                ('_path', models.CharField(default='', max_length=256)),
                ('is_check', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('task', models.CharField(max_length=128)),
                ('_path', models.CharField(default='', max_length=256)),
                ('is_check', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('_path', models.CharField(default='', max_length=256)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User_algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('task', models.CharField(default='', max_length=128)),
                ('_path', models.CharField(default='', max_length=256)),
                ('algorithm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_app.Algorithm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_app.User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('_path', models.CharField(default='', max_length=256)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_app.User_algorithm')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_app.Dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_app.User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
