# Generated by Django 3.1.3 on 2020-12-09 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='created_at',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='hyperp_path',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_algorithm',
            name='created_at',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user_algorithm',
            name='hyperp_path',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user_algorithm',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
