# Generated by Django 3.1.2 on 2020-10-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0002_algorithm_dataset_user_algorithm_user_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-c_time']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='_path',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='_path',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='_path',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user_algorithm',
            name='_path',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user_algorithm',
            name='user_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user_job',
            name='_path',
            field=models.CharField(default='', max_length=256),
        ),
    ]
