# Generated by Django 2.2 on 2020-10-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0002_auto_20201005_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
