# Generated by Django 3.1.2 on 2020-10-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0003_auto_20201004_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='c_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
