# Generated by Django 3.1.2 on 2020-10-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0004_auto_20201004_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_algorithm',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user_job',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='user_algorithm',
            old_name='user_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='user_job',
            old_name='dataset_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user_job',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='user_job',
            name='task',
        ),
        migrations.AddField(
            model_name='user_algorithm',
            name='algorithm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_app.algorithm'),
        ),
        migrations.AddField(
            model_name='user_algorithm',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='_app.user'),
        ),
        migrations.AddField(
            model_name='user_job',
            name='algorithm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='_app.user_algorithm'),
        ),
        migrations.AddField(
            model_name='user_job',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_app.dataset'),
        ),
        migrations.AddField(
            model_name='user_job',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='_app.user'),
        ),
    ]
